debug: False
token : "YOUR_TOKEN_HERE"
command: ['start']
message_filter: ['echo']

config:
  no_sticker:
    message: "不要发贴纸喵！"
    delete: True
  remove_keywork_spam:
    list: "data/keyword_spam.txt"