debug: False
token : "YOUR_TOKEN_HERE"
command: ['start']
message_filter: ['remove_keyword_spam','no_sticker','no_join_group_message','echo']

config:
  echo:
    reply: True
    format: "你说了“{}”喵～"
  command_unknown:
    message: "这是啥指令了喵？"
  no_sticker:
    message: "不要发贴纸喵！"
    delete: True
  remove_keyword_spam:
    message: "关键词违禁了喵！"
    list: "data/keyword_spam.txt"
